server {
    listen 80;
    server_name _;
    return 301 https://$host:8443$request_uri;
}

server {
    listen 443 ssl;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;

    ssl_certificate /etc/nginx/certs/dev-cert.pem;
    ssl_certificate_key /etc/nginx/certs/dev-key.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    location /api/ {
        proxy_pass http://api:3000/api/;
        proxy_set_header Host $host;
    }

    location /fauxpay/ {
        proxy_pass http://fauxpay:4000/;
        proxy_set_header Host $host;
    }

    location / {
        try_files $uri /index.html;
    }
}
